
-- Top 5 products by total revenue
SELECT p.product_name, SUM(i.revenue) AS total_revenue
FROM inventory_sales i
JOIN products p ON i.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_revenue DESC
LIMIT 5;

-- Products with low stock and high sales volume
SELECT p.product_name, i.current_stock, i.sales_volume
FROM inventory_sales i
JOIN products p ON i.product_id = p.product_id
WHERE i.current_stock < 30 AND i.sales_volume > 50
ORDER BY i.sales_volume DESC;

-- Top 10 products with low stock and high inventory turnover rate
SELECT 
    p.product_name,
    i.current_stock,
    i.sales_volume,
    i.inventory_turnover_rate
FROM inventory_sales i
JOIN products p ON i.product_id = p.product_id
WHERE i.current_stock < 30
ORDER BY i.inventory_turnover_rate DESC
LIMIT 10;

-- Total revenue generated by each supplier
SELECT s.supplier_name, SUM(i.revenue) AS supplier_revenue
FROM inventory_sales i
JOIN products p ON i.product_id = p.product_id
JOIN suppliers s ON p.supplier_id = s.supplier_id
GROUP BY s.supplier_name
ORDER BY supplier_revenue DESC;

-- ABC Classification of products based on cumulative sales percentage
SELECT 
    *,
    CASE
        WHEN cumulative <= 0.70 THEN 'A'
        WHEN cumulative <= 0.90 THEN 'B'
        ELSE 'C'
    END AS abc_class
FROM inventory_sales
ORDER BY cumulative;


-- Products classified as 'C' in ABC classification with low performance metrics
SELECT 
    p.product_id,
    p.product_name,
    i.sales_volume,
    i.inventory_turnover_rate,
    abc.abc_class
FROM inventory_sales i
JOIN products p ON i.product_id = p.product_id
JOIN (
    SELECT 
        product_id,
        CASE
            WHEN cumulative <= 0.70 THEN 'A'
            WHEN cumulative <= 0.90 THEN 'B'
            ELSE 'C'
        END AS abc_class
    FROM inventory_sales
) abc ON abc.product_id = i.product_id
WHERE abc.abc_class = 'C'
  AND i.sales_volume < 10
  AND i.inventory_turnover_rate < 1.0
ORDER BY i.sales_volume;